### ISSUE TITLE
How to cite this package in research article?

### ISSUE THREAD

**Issue by yanglipmed** [bjb40/bioage#2]
Finally I found this package to calculate Klemera-Doubal age. Thanks to your work, I can avoid the hard work to realize this algorithm with R by myself. Did you publish some papers with this package? In another word, is this package validated by others' study?

**Comment by bjb40** [comment]
Thanks for the comment! I used this package to prepare analyses in this article: https://academic.oup.com/biomedgerontology/advance-article-abstract/doi/10.1093/gerona/glz219/5613982.
